import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1788202514760 implements MigrationInterface {
    name = 'InitialSchema1788202514760'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "whatsapp_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "text" text NOT NULL, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_dafef64d12b6c3d020b4d0809b5" UNIQUE ("name"), CONSTRAINT "PK_73154f2b6ebc019bc3461ee14eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."boletos_status_enum" AS ENUM('ISSUED', 'PAID', 'OVERDUE', 'CANCELLED', 'ERROR')`);
        await queryRunner.query(`CREATE TABLE "boletos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nossoNumero" character varying NOT NULL, "banco" character varying NOT NULL DEFAULT '756', "customerId" uuid NOT NULL, "monthlyChargeId" uuid, "valorCents" integer NOT NULL, "vencimento" date NOT NULL, "status" "public"."boletos_status_enum" NOT NULL DEFAULT 'ISSUED', "linhaDigitavel" text, "codigoBarras" text, "urlPdf" text, "localPdfPath" text, "urlXml" text, "unimakeId" character varying, "paidAt" date, "paidAmountCents" integer, "payloadJson" jsonb, "errorMessage" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c4b38689a32d5f2f065f98d593a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_879d001a8d5db96263fbec3927" ON "boletos" ("nossoNumero") `);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientName" character varying NOT NULL, "phone" character varying NOT NULL, "cpfOrCnpj" character varying, "address" character varying, "saleDate" date, "warrantyEndDate" date, "productDescription" character varying, "contractFile" character varying, "invoiceFile" character varying, "saleValueCents" integer, "isMonthly" boolean NOT NULL DEFAULT false, "entryValueCents" integer, "monthlyValueCents" integer, "nextPaymentDate" date, "clientId" character varying, CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."monthly_charges_status_enum" AS ENUM('PENDING', 'BOLETO_ISSUED', 'PAID', 'OVERDUE', 'CANCELLED', 'NFSE_ISSUED')`);
        await queryRunner.query(`CREATE TABLE "monthly_charges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" uuid NOT NULL, "saleId" uuid, "competencia" date NOT NULL, "valorCents" integer NOT NULL, "vencimento" date NOT NULL, "status" "public"."monthly_charges_status_enum" NOT NULL DEFAULT 'PENDING', "boletoId" uuid, "nfseId" integer, "paidAt" date, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_26cef00f36861700b3f4d43583" UNIQUE ("boletoId"), CONSTRAINT "PK_5bcda0f654d06b55c518a4972bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_216813d3e1ed64b74618036133" ON "monthly_charges" ("customerId", "competencia") `);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "phone" character varying NOT NULL, "email" character varying, "cpfOrCnpj" character varying, "tradeName" character varying, "cep" character varying, "street" character varying, "number" character varying, "complement" character varying, "neighborhood" character varying, "city" character varying, "state" character varying, "acquisitionDate" date, "entryValue" numeric, "monthlyValue" numeric, "nextPaymentDate" date, "productDescription" character varying, "invoices" text, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."whatsapp_messages_direction_enum" AS ENUM('OUTBOUND', 'INBOUND')`);
        await queryRunner.query(`CREATE TYPE "public"."whatsapp_messages_status_enum" AS ENUM('QUEUED', 'SENT', 'DELIVERED', 'READ', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "whatsapp_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" uuid, "contactId" uuid, "monthlyChargeId" uuid, "direction" "public"."whatsapp_messages_direction_enum" NOT NULL DEFAULT 'OUTBOUND', "phone" character varying NOT NULL, "templateKey" character varying, "text" text, "payload" jsonb, "status" "public"."whatsapp_messages_status_enum" NOT NULL DEFAULT 'QUEUED', "evolutionMessageId" character varying, "errorMessage" text, "scheduledAt" TIMESTAMP WITH TIME ZONE, "dispatchId" uuid, "isBulk" boolean NOT NULL DEFAULT false, "attempts" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_807bc612c6b98de7645a99805ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d7653f64a831456a37d2f1cde2" ON "whatsapp_messages" ("dispatchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b621196ad941c7a3b912be689" ON "whatsapp_messages" ("scheduledAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f7675bfb87b1f7306c080a2ff" ON "whatsapp_messages" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_559aa6c5989dd2d37c8003f6be" ON "whatsapp_messages" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_795825fb7334737bab5af0a236" ON "whatsapp_messages" ("phone") `);
        await queryRunner.query(`CREATE TYPE "public"."user_permissions_resource_enum" AS ENUM('customers', 'sales', 'invoices', 'boletos', 'mensalidades', 'nfse', 'whatsapp', 'tickets', 'company', 'integrations', 'users', 'expenses', 'contacts')`);
        await queryRunner.query(`CREATE TYPE "public"."user_permissions_level_enum" AS ENUM('view', 'edit')`);
        await queryRunner.query(`CREATE TABLE "user_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "resource" "public"."user_permissions_resource_enum" NOT NULL, "level" "public"."user_permissions_level_enum" NOT NULL, CONSTRAINT "uq_user_permission_user_resource" UNIQUE ("userId", "resource"), CONSTRAINT "PK_01f4295968ba33d73926684264f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f05ccc7935f14874d7f89ba030" ON "user_permissions" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'user')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "passwordHash" character varying NOT NULL, "name" character varying NOT NULL, "email" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "active" boolean NOT NULL DEFAULT true, "tokenVersion" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_status_enum" AS ENUM('open', 'in_progress', 'waiting_customer', 'resolved', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text NOT NULL, "status" "public"."tickets_status_enum" NOT NULL DEFAULT 'open', "priority" "public"."tickets_priority_enum" NOT NULL DEFAULT 'medium', "clientId" character varying NOT NULL, "dueDate" TIMESTAMP WITH TIME ZONE, "assigneeName" character varying, "attachments" text DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "nfse" ("id" SERIAL NOT NULL, "invoiceId" integer, "monthlyChargeId" character varying, "ref" character varying, "provider" character varying NOT NULL DEFAULT 'FOCUS_NFE', "status" character varying NOT NULL DEFAULT 'processing', "protocolo" character varying, "nfseNumber" character varying, "xml" text NOT NULL, "response" text, "urlPdf" text, "urlXml" text, "rejectionReason" text, "payloadJson" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a977fbc50a8b6ab2d243d115c0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_type_enum" AS ENUM('nfe', 'nfce', 'nfse')`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'pending', 'sent', 'authorized', 'cancelled', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "number" character varying NOT NULL, "series" character varying NOT NULL, "type" "public"."invoices_type_enum" NOT NULL DEFAULT 'nfe', "accessKey" character varying, "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'draft', "issueDate" date NOT NULL, "dueDate" date, "totalValueCents" integer NOT NULL, "taxValueCents" integer, "discountValueCents" integer, "clientName" character varying NOT NULL, "clientDocument" character varying NOT NULL, "clientEmail" character varying, "clientAddress" text, "description" text NOT NULL, "xmlFilePath" character varying, "pdfFilePath" character varying, "saleId" uuid, "protocolNumber" character varying, "sefazResponse" text, "rejectionReason" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6b20aa66f2a835a4f2fbde48724" UNIQUE ("number"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoice_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceId" uuid NOT NULL, "codigo" character varying NOT NULL, "descricao" character varying NOT NULL, "ncm" character varying NOT NULL, "cfop" character varying NOT NULL, "unidade" character varying NOT NULL, "quantidade" numeric(15,4) NOT NULL DEFAULT '0', "valorUnitarioCents" integer NOT NULL, "valorTotalCents" integer NOT NULL, "icmsOrigem" character varying, "icmsCst" character varying, "icmsAliquota" numeric(7,2), "icmsValor" numeric(12,2), CONSTRAINT "PK_53b99f9e0e2945e69de1a12b75a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "expense_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "color" character varying, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d0ef31e189d9523461215b62775" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."recurring_expenses_frequency_enum" AS ENUM('MONTHLY', 'WEEKLY', 'YEARLY')`);
        await queryRunner.query(`CREATE TYPE "public"."recurring_expenses_paymentmethod_enum" AS ENUM('BOLETO', 'PIX', 'CARTAO', 'TRANSFERENCIA', 'DINHEIRO', 'OUTRO')`);
        await queryRunner.query(`CREATE TABLE "recurring_expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying NOT NULL, "categoryId" uuid NOT NULL, "amountCents" integer NOT NULL, "frequency" "public"."recurring_expenses_frequency_enum" NOT NULL, "dayOfMonth" integer NOT NULL, "dayOfWeek" integer, "monthDay" integer, "startDate" date NOT NULL, "endDate" date, "active" boolean NOT NULL DEFAULT true, "paymentMethod" "public"."recurring_expenses_paymentmethod_enum", "supplier" character varying, "notes" character varying, "attachments" text, "reminderDaysBefore" integer array NOT NULL DEFAULT '{3}', "lastGeneratedDate" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_592b47923f3bdb6035439182e66" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_status_enum" AS ENUM('PENDING', 'PAID', 'OVERDUE', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_paymentmethod_enum" AS ENUM('BOLETO', 'PIX', 'CARTAO', 'TRANSFERENCIA', 'DINHEIRO', 'OUTRO')`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying NOT NULL, "categoryId" uuid NOT NULL, "amountCents" integer NOT NULL, "dueDate" date NOT NULL, "paidDate" date, "status" "public"."expenses_status_enum" NOT NULL DEFAULT 'PENDING', "paymentMethod" "public"."expenses_paymentmethod_enum", "supplier" character varying, "notes" character varying, "attachments" text, "recurringExpenseId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3bffb46f1bb12797b37055a030" ON "expenses" ("status", "dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_c37b91339f18822af34690dc3d" ON "expenses" ("dueDate") `);
        await queryRunner.query(`CREATE TYPE "public"."expense_reminders_channel_enum" AS ENUM('INAPP', 'WHATSAPP')`);
        await queryRunner.query(`CREATE TYPE "public"."expense_reminders_status_enum" AS ENUM('SENT', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "expense_reminders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "expenseId" uuid NOT NULL, "daysBefore" integer NOT NULL, "channel" "public"."expense_reminders_channel_enum" NOT NULL, "status" "public"."expense_reminders_status_enum" NOT NULL, "errorMessage" text, "sentAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6eb8fccb8d14a9fad12d6868bfb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_44393d14b1a72c1fa55aac4592" ON "expense_reminders" ("expenseId", "daysBefore", "channel") `);
        await queryRunner.query(`CREATE TABLE "contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "phone" character varying NOT NULL, "notes" text, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b99cd40cfd66a99f1571f4f72e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_84cae51c485079bdd8cdf1d828" ON "contacts" ("phone") `);
        await queryRunner.query(`ALTER TABLE "boletos" ADD CONSTRAINT "FK_e5fdc06798c284c23bb02be820f" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "monthly_charges" ADD CONSTRAINT "FK_706293527302736a4d4b2b3900a" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "monthly_charges" ADD CONSTRAINT "FK_ce85aedf0e18f80fd705ab04dd5" FOREIGN KEY ("saleId") REFERENCES "sales"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "monthly_charges" ADD CONSTRAINT "FK_26cef00f36861700b3f4d435838" FOREIGN KEY ("boletoId") REFERENCES "boletos"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "whatsapp_messages" ADD CONSTRAINT "FK_9dcba37dc61bb392b37cb6b5d96" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permissions" ADD CONSTRAINT "FK_f05ccc7935f14874d7f89ba030f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_23de94fa7468d27abfa62f9e275" FOREIGN KEY ("saleId") REFERENCES "sales"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" ADD CONSTRAINT "FK_a6403322c9cfc066f9db12b5f91" FOREIGN KEY ("categoryId") REFERENCES "expense_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_ac0801a1760c5f9ce43c03bacd0" FOREIGN KEY ("categoryId") REFERENCES "expense_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_aed189aba2adb157446528abf73" FOREIGN KEY ("recurringExpenseId") REFERENCES "recurring_expenses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_reminders" ADD CONSTRAINT "FK_cf95730ca412ff74d6a79ca0c6d" FOREIGN KEY ("expenseId") REFERENCES "expenses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "expense_reminders" DROP CONSTRAINT "FK_cf95730ca412ff74d6a79ca0c6d"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_aed189aba2adb157446528abf73"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_ac0801a1760c5f9ce43c03bacd0"`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" DROP CONSTRAINT "FK_a6403322c9cfc066f9db12b5f91"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_23de94fa7468d27abfa62f9e275"`);
        await queryRunner.query(`ALTER TABLE "user_permissions" DROP CONSTRAINT "FK_f05ccc7935f14874d7f89ba030f"`);
        await queryRunner.query(`ALTER TABLE "whatsapp_messages" DROP CONSTRAINT "FK_9dcba37dc61bb392b37cb6b5d96"`);
        await queryRunner.query(`ALTER TABLE "monthly_charges" DROP CONSTRAINT "FK_26cef00f36861700b3f4d435838"`);
        await queryRunner.query(`ALTER TABLE "monthly_charges" DROP CONSTRAINT "FK_ce85aedf0e18f80fd705ab04dd5"`);
        await queryRunner.query(`ALTER TABLE "monthly_charges" DROP CONSTRAINT "FK_706293527302736a4d4b2b3900a"`);
        await queryRunner.query(`ALTER TABLE "boletos" DROP CONSTRAINT "FK_e5fdc06798c284c23bb02be820f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84cae51c485079bdd8cdf1d828"`);
        await queryRunner.query(`DROP TABLE "contacts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44393d14b1a72c1fa55aac4592"`);
        await queryRunner.query(`DROP TABLE "expense_reminders"`);
        await queryRunner.query(`DROP TYPE "public"."expense_reminders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expense_reminders_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c37b91339f18822af34690dc3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bffb46f1bb12797b37055a030"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_status_enum"`);
        await queryRunner.query(`DROP TABLE "recurring_expenses"`);
        await queryRunner.query(`DROP TYPE "public"."recurring_expenses_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recurring_expenses_frequency_enum"`);
        await queryRunner.query(`DROP TABLE "expense_categories"`);
        await queryRunner.query(`DROP TABLE "invoice_items"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_type_enum"`);
        await queryRunner.query(`DROP TABLE "nfse"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_status_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f05ccc7935f14874d7f89ba030"`);
        await queryRunner.query(`DROP TABLE "user_permissions"`);
        await queryRunner.query(`DROP TYPE "public"."user_permissions_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_permissions_resource_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_795825fb7334737bab5af0a236"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_559aa6c5989dd2d37c8003f6be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f7675bfb87b1f7306c080a2ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b621196ad941c7a3b912be689"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7653f64a831456a37d2f1cde2"`);
        await queryRunner.query(`DROP TABLE "whatsapp_messages"`);
        await queryRunner.query(`DROP TYPE "public"."whatsapp_messages_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."whatsapp_messages_direction_enum"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_216813d3e1ed64b74618036133"`);
        await queryRunner.query(`DROP TABLE "monthly_charges"`);
        await queryRunner.query(`DROP TYPE "public"."monthly_charges_status_enum"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_879d001a8d5db96263fbec3927"`);
        await queryRunner.query(`DROP TABLE "boletos"`);
        await queryRunner.query(`DROP TYPE "public"."boletos_status_enum"`);
        await queryRunner.query(`DROP TABLE "whatsapp_templates"`);
    }

}
